Add Missing Type Annotations
adafruit/Adafruit_CircuitPython_HTU31D pull request #8
Opened 2022-09-24 14:00 UTC by tcfranks

resolves #7 
submitted for review / comment

2022-09-27 02:02 UTC, tekktrik requested changes

2022-09-27 02:02 UTC, tekktrik commented on adafruit_htu31d.py
> +            raise ValueError("Invalid address: {address:#x}")
This needs an `f` to make it an f-string, and use `hex()`

2022-09-27 02:02 UTC, tekktrik commented on adafruit_htu31d.py
> +    def serial_number(self) -> int:
This is actually `Tuple[int]` currently, but it actually seems like a bug since the example file expects it to be an `int`.  Let's keep the typing but can you have this property function return `ser[0]`?  Thanks!

2022-09-27 02:02 UTC, tekktrik commented on adafruit_htu31d.py
>          if not new_mode in (True, False):
Can you actually change this to `isinstace(new_mode, bool)` to support the typing?  Thanks!

2022-09-27 14:44 UTC, tcfranks commented on adafruit_htu31d.py
> +            raise ValueError("Invalid address: {address:#x}")
oops!  pylint barks about .format() used instead of fast strings but can't recognize when fast strings are incorrect?

2022-09-27 14:59 UTC, tcfranks commented
resubmitted with changes for additional review

2022-09-28 00:33 UTC, tekktrik approved these changes
Thank you!

2022-09-28 00:33 UTC, merged